/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.masil.testing.compile;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
